# /home/chris/.dotfiles/home-manager/home.nix
{ config, pkgs, lib, inputs, ... }:

let
  # Path to the directory where your actual dotfiles are stored
  dotfilesDir = "${config.home.homeDirectory}/.dotfiles/config";
  #dotfilesDir = ../config;
in
{
  # Home Manager needs a bit of information about you and the paths it should
  # manage.
  home.username = "chris";
  home.homeDirectory = "/home/chris";

  # This value determines the Home Manager release that your configuration is
  # compatible with. This helps avoid breakage when a new Home Manager release
  # introduces backwards incompatible changes.
  #
  # You can update Home Manager without changing this value. See
  # the Home Manager release notes for a list of state version
  # changes in each release.
  home.stateVersion = "24.11"; # Updated from "23.05"

  # Packages
  home.packages = with pkgs; [
    oh-my-zsh
    zsh-powerlevel10k
    fzf
    zoxide
    nerd-fonts.meslo-lg # Use the identified Nerd Font attribute
    vscode
    obsidian
  ];

  # Nicely reload systemd units when changing configurations.
  systemd.user.startServices = "sd-switch";

  # Symlink dotfiles from the 'config' directory, Stow-compatible
  # The target path (e.g., ".zshrc") is relative to home.homeDirectory
  # The source path is relative to this home.nix file, pointing into the 'config' dir.

  # Symlink core Zsh configuration files
  # Your .zshrc in config/zsh/.zshrc will handle OMZ and P10k setup.
  home.file.".zshrc".source = config.lib.file.mkOutOfStoreSymlink "${dotfilesDir}/zsh/.zshrc";

  # Symlink .p10k.zsh if you manage it via Stow
  # This file is generated by `p10k configure`.
  home.file.".p10k.zsh".source = config.lib.file.mkOutOfStoreSymlink "${dotfilesDir}/zsh/.p10k.zsh";

  # Symlink alacritty config
  home.file.".config/alacritty/alacritty.toml".source = config.lib.file.mkOutOfStoreSymlink "${dotfilesDir}/alacritty/.config/alacritty/alacritty.toml";

  # Example for .gitconfig (source: config/git/.gitconfig -> target: ~/.gitconfig)
  # home.file.".gitconfig".source = config.lib.file.mkOutOfStoreSymlink "${dotfilesDir}/git/.gitconfig";

  # Example for Neovim (stow structure often puts .config inside the app folder)
  # (source: config/nvim/.config/nvim/init.lua -> target: ~/.config/nvim/init.lua)
  # home.file.".config/nvim/init.lua".source = config.lib.file.mkOutOfStoreSymlink "${dotfilesDir}/nvim/.config/nvim/init.lua";
  # Or, if your nvim config is directly in config/nvim/init.lua and you want it at ~/.config/nvim/init.lua
  # home.file.".config/nvim/init.lua".source = config.lib.file.mkOutOfStoreSymlink "${dotfilesDir}/nvim/init.lua";

  programs.zsh = {
    enable = true; # Sets Zsh as default shell
    # Oh My Zsh and Powerlevel10k configuration will be handled by your symlinked .zshrc
    # and .p10k.zsh files.
    # The oh-my-zsh package installed via home.packages provides the framework.
    envExtra = ''
      export ZSH="${pkgs.oh-my-zsh}/share/oh-my-zsh" # Point to the subdirectory
      export POWERLEVEL10K_PATH="${pkgs.zsh-powerlevel10k}/share/zsh-powerlevel10k" # Point to the subdirectory
    '';
  };

  programs.git = {
    enable = true;
    # If you symlink .gitconfig, these settings might be redundant or conflict
    # unless your .gitconfig sources system/global git configs.
    # userName = "Chris"; # To be managed by .gitconfig symlink if used
    # userEmail = "chris@example.com"; # To be managed by .gitconfig symlink if used
  };

  # Let Home Manager install and manage itself.
  programs.home-manager.enable = true;

  # You can import other modules here if you split your configuration
  # imports = [
  #   ./modules/git.nix
  #   ./modules/zsh.nix
  # ];
}
